version: '3'

services:
  order-service-app-container:
    image: order-service-app:1
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - /data/order-service-app
    ports:
      - "8091:8091"